CITIES_SIGSPATIAL = [
    'Zagrzeb', 'Helsinki', 'Espoo', 'Tampere', 'Oulu', 
    'Lille', 'Nice', 'Toulouse', 'Nantes', 'Cologne', 
    'Aachen', 'Hamburg', 'Erfurt', 'Mannheim', 'Antwerp', 
    'Gent', 'Wieden', 'Karlsruhe', 'Ateny', 'Budapest',
    'Wenecja', 'Florencja', 'Genoa', 'Turin', 'Palermo',
    'Milan', 'Oslo', 'Szczecin', 'Lublin', 'Radom',
    'Belgrad', 'Valencia', 'Zurych', 'Dublin', 
    'Bilbao', 'Madryt', 'Wilno', 'Barcelona', 'Praga', 
    'Warszawa', 'Lipsk', 'Wroclaw', 'Poznan', 'Krakow', 
    'Bydgoszcz', 'Gdansk', 'Berlin', 'Bruksela'
]
CITIES_GTFS = {
    'Wroclaw': ['Wroclaw'], 
    'Poznan': ['Poznan'], 
    'Krakow': ['Krakow-bus', 'Krakow-tram'], 
    'Bydgoszcz': ['Bydgoszcz'], 
    'Gdansk': ['Gdansk', 'Gdansk-skm'], 
    'Berlin': ['Berlin'], 
    'Praga': ['Praga'],
    'Warszawa': ['Warszawa'],
    'Lipsk': ['Lipsk'],
    'Barcelona': ['Barcelona-metro-bus', 'Barcelona-tram-1', 'Barcelona-tram-2'],
    'Bruksela': ['Bruksela'],
    'Rzym': ['Rzym'],
    'Ryga': ['Ryga'],
    'Wilno': ['Wilno'],
    'Zagrzeb': ['Zagrzeb'],
    'Helsinki': ['Helsinki'],
    'Espoo': ['Helsinki'],
    'Tampere': ['Tampere'],
    'Oulu': ['Oulu'],
    'Paryz': ['Paryz'],
    'Lille': ['Lille'],
    'Nice': ['Nice'],
    'Toulouse': ['Toulouse'],
    'Nantes': ['Nantes'],
    'Cologne': ['Cologne'],
    'Aachen': ['Aachen'],
    'Freiburg': ['Freiburg'],
    'Hamburg': ['Hamburg'],
    'Erfurt': ['Erfurt'],
    'Mannheim': ['Mannheim'],
    'Antwerp': ['Antwerp-waterbus', 'De-Lijn'],
    'Gent': ['De-Lijn'],
    'Wieden': ['Wieden'],
    'Karlsruhe': ['Karlsruhe'],
    'Ateny': ['Ateny'],
    'Budapest': ['Budapest'],
    'Wenecja': ['Wenecja-auto', 'Wenecja-prom'],
    'Florencja': ['Florencja'],
    'Genoa': ['Genoa'],
    'Turin': ['Turin'],
    'Palermo': ['Palermo'],
    'Milan': ['Milan', 'Milan-movibus', 'Milan-airpullman'],
    'Oslo': ['Oslo'],
    'Szczecin': ['Szczecin'],
    'Lublin': ['Lublin'],
    'Radom': ['Radom'],
    'StPetersburg': ['StPetersburg'],
    'Belgrad': ['Belgrad'],
    'Valencia': ['valencia-metro', 'Valencia-bus'],
    'Malaga': ['Malaga-metro', 'Malaga-bus'],
    'Sztokholm': ['Sztokholm'],
    'Zurych': ['Zurych'],
    'Manchester': ['Manchester'],
    'Dublin': ['Dublin-rail', 'Dublin-bus', 'Dublin-tram'],
    'Bilbao': ['Bilbao-metro', 'Bilbao-tram', 'Bilbao-bilbobus', 'Bilbao-bizkaibus'],
    'Madryt': ['Madryt-EMT', 'Madryt-rail', 'Madryt-bus', 'Madryt-metro1', 'Madryt-metro2'],
    'Lizbona': ['Lizbona-bus2', 'Lizbona-bus3', 'Lizbona-carris', 'Lizbona-metro', 'Lizbona-rail', 'Lizbona-rail2']
}
CITIES_GEOJSON = {
    'Wroclaw': 'wroclaw', 
    'Poznan': 'poznan', 
    'Krakow': 'krakow', 
    'Bydgoszcz': 'bydgoszcz', 
    'Gdansk': 'gdansk', 
    'Berlin': 'berlin', 
    'Praga': 'praga',
    'Warszawa': 'warszawa',
    'Lipsk': 'lipsk',
    'Barcelona': 'barcelona',
    'Bruksela': 'bruksela',
    'Rzym': 'rzym',
    'Ryga': 'ryga',
    'Wilno': 'wilno',
    'Zagrzeb': 'zagrzeb',
    'Helsinki': 'helsinki',
    'Espoo':  'espoo',
    'Tampere': 'tampere',
    'Oulu': 'oulu',
    'Paryz': 'paryz',
    'Lille': 'lille',
    'Nice': 'nice',
    'Toulouse': 'toulouse',
    'Nantes': 'nantes',
    'Cologne': 'cologne',
    'Aachen': 'aachen',
    'Freiburg': 'freiburg',
    'Hamburg': 'hamburg',
    'Erfurt': 'erfurt',
    'Mannheim': 'mannheim',
    'Antwerp': 'antwerp',
    'Gent': 'gent',
    'Wieden': 'wieden',
    'Karlsruhe': 'karlsruhe',
    'Ateny': 'ateny',
    'Budapest': 'budapest',
    'Wenecja': 'wenecja',
    'Florencja': 'florencja',
    'Genoa': 'genoa',
    'Turin': 'turin',
    'Palermo': 'palermo',
    'Milan': 'milan',
    'Oslo': 'oslo',
    'Szczecin': 'szczecin',
    'Lublin': 'lublin',
    'Radom': 'radom',
    'StPetersburg': 'stpetersburg',
    'Belgrad': 'belgrad',
    'Valencia': 'valencia',
    'Malaga': 'malaga',
    'Sztokholm': 'sztokholm',
    'Zurych': 'zurych',
    'Manchester': 'manchester',
    'Dublin': 'dublin',
    'Bilbao': 'bilbao',
    'Madryt': 'madryt',
    'Lizbona': 'lizbona'
}
NORM_COLUMNS = {
    'trips_at': range(6, 23),
    'directions_at': range(6, 23)
}
USED_COLUMNS = [f'trips_at_{i}' for i in range(6, 23)] + [f'directions_at_{i}' for i in range(6, 23)] + ['city']
MIN_CLUSTERS = 2
MAX_CLUSTERS = 16
DENSE_ENCODER_LAYERS = [24, 16]
SPARSE_ENCODER_LAYERS = [48, 64]
CLUSTERS_SWAPS = {
    4: {0: 1, 1: 0},
    6: {0: 2, 2: 0},
    7: {6: 0, 0: 1, 1: 2, 2: 6},
    8: {3: 1, 1: 3, 6: 0, 0: 2, 2: 6},
    9: {6: 0, 0: 3, 3: 2, 2: 6},
    10: {6: 0, 0: 3, 3: 2, 2: 6},
    11: {2: 0, 0: 6, 6: 3, 3: 2},
    12: {2: 0, 0: 1, 1: 2, 3: 7, 7: 6, 6: 3}
}